---
  - name: Create the keystone database
    mysql_db:
      name: keystone
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Set mysql user privileges
    mysql_user:
      name: keystone
      password: '{{secret}}'
      host: '%'
      priv: 'keystone.*:ALL'
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Set mysql user privileges
    mysql_user:
      name: keystone
      password: '{{secret}}'
      host: 'localhost'
      priv: 'keystone.*:ALL'
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Install Keystone
    yum:
      name:
      - openstack-keystone
      - httpd
      - mod_wsgi
      state: present
  - name: Configure keystone.conf
    template:
      src: templates/keystone.conf
      dest: /etc/keystone/keystone.conf
      owner: root
      mode: 0640
  - name: Populate the Identity service database
    shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
    ignore_errors: yes
  - name: Initialize Fernet key repositories1
    command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  - name: Initialize Fernet key repositories2
    command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  - name: Bootstrap the Identity service
    command: keystone-manage bootstrap --bootstrap-password {{secret}} --bootstrap-admin-url http://{{controller}}:5000/v3/ --bootstrap-internal-url http://{{controller}}:5000/v3/ --bootstrap-public-url http://{{controller}}:5000/v3/ --bootstrap-region-id RegionOne
    ignore_errors: yes
  - name: Add a line to a file if the file does not exist, without passing regexp
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: ServerName {{controller}}
      create: yes
  - name: Create symbolic link /usr/share/keystone/wsgi-keystone.conf
    file:
      src: /usr/share/keystone/wsgi-keystone.conf 
      dest: /etc/httpd/conf.d/wsgi-keystone.conf
      state: link
  - name: Enable and start services
    systemd:
      name: httpd
      state: started
      enabled: yes
  - name: Create Service Project
    command: openstack project create --domain default --description "Service Project" service
    environment: "{{ admin_rc }}"
  - name: Create admin-openrc
    template:
      src: templates/admin-openrc
      dest: /root/admin-openrc 
      owner: root
      mode: 0600
