---
  - name: Install Openstack Database
    yum:
      name:
      - mariadb
      - mariadb-server
      - python2-PyMySQL
      state: present
  - name: Create mariadb configuration file
    copy:
      dest: "/etc/my.cnf.d/openstack.cnf"
      content: |
        [mysqld]
        bind-address = {{controller_ip}}
        default-storage-engine = innodb
        innodb_file_per_table = on
        max_connections = 4096
        collation-server = utf8_general_ci
        character-set-server = utf8 
  - name: Enable and start mariadb service
    systemd:
      name: mariadb.service
      state: started
      enabled: yes
  - name: Configure blank my.cnf
    template:
      src: templates/my_blank.cnf
      dest: /root/.my.cnf
      owner: root
      mode: 0600
  - name: Set root Password
    mysql_user: check_implicit_admin=yes name=root password={{ secret }} state=present login_unix_socket=/var/lib/mysql/mysql.sock
  - name: Configure new my.cnf
    template:
      src: templates/my.cnf
      dest: /root/.my.cnf
      owner: root
      mode: 0600
  - name: Reload privilege tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

  - name: Remove anonymous users
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DELETE FROM mysql.user WHERE User=''
    changed_when: False

  - name: Disallow root login remotely
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    changed_when: False

  - name: Remove test database and access to it
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DROP DATABASE IF EXISTS test
      - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
    changed_when: False

  - name: Reload privilege tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False
  - name: Install RabbitMQ
    yum:
      name:
      - rabbitmq-server
      state: present
  - name: Enable and start RabbitMQ service
    systemd:
      name: rabbitmq-server.service
      state: started
      enabled: yes
  - name: Create RabbitMQ User
    community.rabbitmq.rabbitmq_user:
      user: openstack
      password: '{{secret}}'
      permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      state: present
  - name: Install Memcached
    yum:
      name:
      - memcached
      - python-memcached
      state: present
  - name: Configure memcached
    template:
      src: templates/memcached
      dest: /etc/sysconfig/memcached
      owner: root
      mode: 0600
  - name: Enable and start memcached service
    systemd:
      name: memcached.service
      state: started
      enabled: yes
  - name: Install etcd
    yum:
      name:
      - etcd
      state: present
  - name: Configure etcd.conf
    template:
      src: templates/etcd.conf
      dest: /etc/etcd/etcd.conf
      owner: root
      mode: 0600
