---
  - name: Install Nova
    yum:
      name:
      - openstack-nova-compute
      state: present
  - name: Configure nova.conf
    template:
      src: templates/nova.conf
      dest: /etc/nova/nova.conf
      owner: root
      mode: 0640
  - name: Enable and start libvirtd.service
    systemd:
      name: libvirtd.service
      state: started
      enabled: yes
  - name: Enable and start openstack-nova-compute.service
    systemd:
      name: openstack-nova-compute.service
      state: started
      enabled: yes
